Improve check build
Signed-off-by: Lukas Heumos <lukas.heumos@posteo.net>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -4,30 +4,33 @@ on:
     push:
         branches: [main]
     pull_request:
-        types:
-            - opened
-            - synchronize
+        branches: [main]
 
 concurrency:
     group: ${{ github.workflow }}-${{ github.ref }}
     cancel-in-progress: true
 
+defaults:
+    run:
+        # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
+        shell: bash -euo pipefail {0}
+
 jobs:
     package:
         runs-on: ubuntu-latest
         steps:
-            - uses: actions/checkout@v3
-
-            - name: Set up Python
-              uses: actions/setup-python@v5
+            - uses: actions/checkout@v4
               with:
-                  python-version: "3.13"
+                  filter: blob:none
+                  fetch-depth: 0
 
-            - name: Install build dependencies
-              run: python -m pip install --upgrade pip wheel twine build
+            - name: Install uv
+              uses: astral-sh/setup-uv@v6
+              with:
+                  cache-dependency-glob: pyproject.toml
 
             - name: Build package
-              run: python -m build
+              run: uv build
 
             - name: Check package
-              run: twine check --strict dist/*.whl
+              run: uvx twine check --strict dist/*.whl
